name: binary-waterfall-unofficial
channels:
- defaults
- conda-forge
dependencies:
- python=3.13*
- pip
- ffmpeg
- pip:
  - pyinstaller
  - pyinstaller-versionfile
  - PyQt6
  - pydub
  - Pillow
  - moviepy
  - proglog
